interface=enp0s25
bind-interfaces

# Enable DHCP and BOOTP
dhcp-range=172.16.1.2,172.16.1.2,255.255.255.0
enable-tftp
tftp-root=/irix
log-queries
log-dhcp

# Define static lease for SGI machine (replace values accordingly)
dhcp-host=08:00:69:12:34:56,sgi-irix,172.16.1.2,infinite
