- name: Copy display_results
  copy:
    src: files/display_results.sh
    dest: /srv/irix/display_results.sh
    owner: root
    group: root
    mode: 0755

- name: Get results
  command: /srv/irix/display_results.sh
  register: cmd_output

- name: Display results
  debug:
    var: cmd_output.stdout_lines
