booterizer:
  installmirror:  "https://sgi-irix.s3.amazonaws.com"
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  clientname:     "sgi"
  clientdomain:   "home.local"
  network:        "10.10.10.0" 
  netmask:        "255.255.255.0"
  routerip:       "10.10.10.1"
  hostip:         "10.10.10.2"
  clientip:       "10.10.10.100"
  clientether:    "08:00:69:0c:9d:5f"
  bridgenic:      "host0"
  uplinknic:      "host0"
  myuser:         "testuser"
  myshell: "/usr/nekoware/bin/bash"
