allow booting;
allow bootp;

subnet 172.16.1.0 netmask 255.255.255.0 {
  ignore unknown-clients;
}

host sgi {
  hardware ethernet 08:00:69:0c:4e:2f;
  fixed-address 172.16.1.2;
  option domain-name-servers 172.16.1.1;
  option domain-name "home.local";
  filename "6.5.30/Overlay/disc1/stand/fx.64";
}
