[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:isc-dhcp-server]
command=/usr/sbin/dhcpd -4 -f -d --no-pid -cf /etc/dhcp/dhcpd.conf
autorestart=true
stdout_logfile=/var/log/supervisor/dhcpd.log
stderr_logfile=/var/log/supervisor/dhcpd.err

[program:tftpd-hpa]
<<<<<<< HEAD
command=/usr/sbin/in.tftpd --foreground --secure --verbose /srv/irix
autorestart=true
stdout_logfile=/var/log/supervisor/tftpd.log
stderr_logfile=/var/log/supervisor/tftpd.err

[program:xinetd]
command=/usr/sbin/xinetd -dontfork -stayalive
autorestart=true
stdout_logfile=/var/log/supervisor/xinetd.log
stderr_logfile=/var/log/supervisor/xinetd.err
=======
command=/usr/sbin/in.tftpd --foreground --secure /srv/irix
autorestart=true

[program:inetd]
command=/usr/sbin/inetd -d
>>>>>>> 5454b95386bf41e789e4e38206cb817937e145b2
