[supervisord]
nodaemon=true

[program:isc-dhcp-server]
command=/usr/sbin/dhcpd -4 -f -d --no-pid
autorestart=true

[program:tftpd-hpa]
command=/usr/sbin/in.tftpd --foreground --secure /srv/irix
autorestart=true

[program:inetd]
command=/usr/sbin/inetd -d
