# xinetd configuration for booterizer
# Provides RSH/rlogin services for IRIX inst

defaults
{
    log_type        = SYSLOG daemon info
    log_on_failure  = HOST
    log_on_success  = PID HOST DURATION EXIT
    instances       = 50
    per_source      = 10
}

includedir /etc/xinetd.d
