- name: Generate isc-dhcp-server config
  template:
    src: templates/dhcpd.conf.j2
    dest: "{{ container_path }}/etc/dhcp/dhcpd.conf"
    owner: root
    group: root

- name: Create default for isc-dhcp-server
  become: true
  ansible.builtin.copy:
    dest: "{{ container_path }}/etc/default/isc-dhcp-server"
    mode: '0644'
    content: |
      INTERFACESv4="{{ bridgenic }}"
      INTERFACESv6=""

- name: Create systemd unit for isc-dhcp-server inside container
  become: true
  ansible.builtin.copy:
    dest: "{{ container_path }}/etc/systemd/system/isc-dhcp-server.service"
    mode: '0644'
    content: |
      [Unit]
      Description=ISC DHCP Server
      After=network.target

      [Service]
      ExecStart=/etc/init.d/isc-dhcp-server start
      ExecStop=/etc/init.d/isc-dhcp-server stop
      Type=forking

      [Install]
      WantedBy=multi-user.target

- name: Enable isc-dhcp-server in container
  become: true
  ansible.builtin.file:
    src: "{{ container_path }}/etc/systemd/system/isc-dhcp-server.service"
    dest: "{{ container_path }}/etc/systemd/system/multi-user.target.wants/isc-dhcp-server.service"
    state: link
    force: true


- name: Configure tftpd-hpa
  copy:
    src: files/tftpd-hpa
    dest: "{{ container_path }}/etc/default/tftpd-hpa"
    owner: root
    group: root

- name: Create systemd unit for tftpd-hpa inside container
  become: true
  ansible.builtin.copy:
    dest: "{{ container_path }}/etc/systemd/system/tftpd-hpa.service"
    mode: '0644'
    content: |
      [Unit]
      Description=TFTP server
      After=network.target

      [Service]
      ExecStart=/etc/init.d/tftpd-hpa start
      ExecStop=/etc/init.d/tftpd-hpa stop
      Type=forking

      [Install]
      WantedBy=multi-user.target

- name: Enable tftpd-hpa in container
  become: true
  ansible.builtin.file:
    src: "{{ container_path }}/etc/systemd/system/tftpd-hpa.service"
    dest: "{{ container_path }}/etc/systemd/system/multi-user.target.wants/tftpd-hpa.service"
    state: link
    force: true

- name: generate hosts
  template:
    src: templates/hosts.j2
    dest: "{{ container_path }}/etc/hosts"
    owner: root
    group: root
    mode: 0744

- name: generate .rhosts
  template:
    src: templates/rhosts.j2
    dest: "/srv/irix/.rhosts"
    owner: root
    group: root
    mode: 0600

- name: generate hosts.equiv
  template:
    src: templates/hosts.equiv.j2
    dest: "{{ container_path }}/etc/hosts.equiv"
    owner: root
    group: root
    mode: 0744

# - name: Add the guest user
#   user:
#     name: guest
#     shell: /bin/ksh
#     home: /irix

- name: Configure host0 inside container
  become: true
  ansible.builtin.copy:
    dest: "{{ container_path }}/etc/systemd/network/20-host0.network"
    content: |
      [Match]
      Name=host0

      [Network]
      Address=10.10.10.2/24
      Gateway=10.10.10.1
      DNS=8.8.8.8
    mode: '0644'

- name: Configure bridgenic inside container
  become: true
  ansible.builtin.copy:
    dest: "{{ container_path }}/etc/systemd/network/20-{{ bridgenic }}.network"
    mode: '0644'
    content: |
      [Match]
      Name={{ bridgenic }}

      [Link]
      RequiredForOnline=no

      [Network]
      ConfigureWithoutCarrier=yes
      LinkLocalAddressing=no
      DHCP=no

- name: Enable systemd-networkd in the container
  become: true
  ansible.builtin.file:
    src: "{{ container_path }}/lib/systemd/system/systemd-networkd.service"
    dest: "{{ container_path }}/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
    state: link

- name: Enable systemd-resolved in the container
  become: true
  ansible.builtin.file:
    src: "{{ container_path }}/lib/systemd/system/systemd-resolved.service"
    dest: "{{ container_path }}/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
    state: link

