- name: Generate isc-dhcp-server config dir
  file:
    path: "{{ container_path }}/etc/dhcpd"
    owner: root
    group: root

- name: Generate isc-dhcp-server config
  template:
    src: templates/dhcpd.conf.j2
    dest: "{{ container_path }}/etc/dhcpd/dhcpd.conf"
    owner: root
    group: root

- name: Configure tftpd-hpa
  copy:
    src: files/tftpd-hpa
    dest: "{{ container_path }}/etc/default/tftpd-hpa"
    owner: root
    group: root

- name: generate hosts
  template:
    src: templates/hosts.j2
    dest: "{{ container_path }}/etc/hosts"
    owner: root
    group: root
    mode: 0744

- name: generate .rhosts
  template:
    src: templates/rhosts.j2
    dest: "{{ container_path }}/irix/.rhosts"
    owner: root
    group: root
    mode: 0600

- name: generate hosts.equiv
  template:
    src: templates/hosts.equiv.j2
    dest: "{{ container_path }}/etc/hosts.equiv"
    owner: root
    group: root
    mode: 0744

# - name: Add the guest user
#   user:
#     name: guest
#     shell: /bin/ksh
#     home: /irix


