---
ungrouped:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    system_locale: "en_US.UTF-8"
    system_timezone: "America/New_York"
    system_packages:
     - debootstrap
     - systemd-container
     - xfsprogs 