- name: Copy inst commands file
  copy:
    src: files/commands
    dest: /irix/commands
    owner: vagrant
    group: vagrant
    mode: 0744
  when: rpi == False

- name: Copy inst commands file for pi
  copy:
    src: files/commands
    dest: /irix/commands
    owner: root
    group: root
    mode: 0744
  when: rpi == True

