# Setup the virt OS
- name: Set hostname
  hostname:
    name: booterizer
  when: rpi == False

- name: Restart service rsyslog
  service:
    name: rsyslog
    state: restarted
  when: rpi == False

# Why this?
# Note on versions: 14.04  trusty = jessie/sid
# https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on

- apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
    state: present
  when: rpi == False

- name: Add an apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
  when: rpi == False

- name: Install required packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - tftpd-hpa
    - isc-dhcp-server
    - rsh-server
    - dnsmasq
    - mksh
    - parted
    - xfsprogs
    - rsync
    - tcpdump
    - ansible
    - git
    - curl
  when: rpi == False 

- name: Install required packages for RPi
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages: 
    - tftpd-hpa 
    - isc-dhcp-server 
    - rsh-server 
    - dnsmasq 
    - mksh 
    - parted 
    - xfsprogs 
    - rsync 
    - tcpdump
    - git
    - curl
  when: rpi == True
